EZP-27445: Create form to allow editing of versions
inviqa/hybrid-platform-ui pull request #6
Opened 2017-06-20 13:20 UTC by maxbaldanza

Still a WIP but submitting for feedback

2017-06-21 15:39 UTC, mcurran-inviqa requested changes

2017-06-21 15:39 UTC, mcurran-inviqa commented on src/lib/Repository/VersionService.php
> +
should handle if version no longer exists, also they may not have access to do so?

2017-06-21 15:39 UTC, mcurran-inviqa commented on src/lib/Repository/VersionService.php
> +
DocBlock

2017-06-21 15:39 UTC, mcurran-inviqa commented on src/lib/Mapper/Form/VersionMapper.php
> +
DocBlock

2017-06-21 15:39 UTC, mcurran-inviqa commented on src/bundle/Resources/config/services.yml
> +            class: EzSystems\HybridPlatformUi\Mapper\Form\VersionMapper
remove a tab

2017-06-22 11:52 UTC, maxbaldanza commented on src/lib/Repository/VersionService.php
> +
The `contentService` will throw these errors directly so I'd have thought we could catch these directly in the controller or are you suggesting throwing our own errors in here?

2017-06-22 13:27 UTC, closed without merging